baseURL = 'https://maurannerasoa.github.io/'
languageCode = 'fr-fr'
title = 'Mauranne website'
theme = 'anatole'

[params]
title = "Site de Mauranne"
author = "Mauranne"
description = "Salut je trouve que Hugo est très lourd pour ce que ça fait"
profilePicture = "images/profile.jpg"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/cat"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:cutecat@cat.fr"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'